##
# Please refer to Circle CI Documentation for
# advanced tweaks and configuration
##

version: 2
################################ Workflows ################################
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-deploy-PRODUCTION:
          filters:
            branches:
              only: staging

################################ JOBS ################################
jobs:
  #(PRODUCTION) Build and Deploy Configuration
  build-deploy-PRODUCTION:
    working_directory: ~/b2b
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo apt install rsync
      # (Production) Build Angular project
      - restore_cache:
          key: dependency-cache-production-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies (PRODUCTION)
          command: npm install

      - save_cache:
          key: dependency-cache-production-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
            - ./node_modules
      - add_ssh_keys:
          fingerprints:
            - "71:ab:7b:a0:f3:ab:91:be:bb:48:7b:32:c1:86:d7:1d"